name: slectiv_studio_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cloud_firestore: ^5.6.4
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  fluentui_system_icons: ^1.1.273
  lottie: ^3.3.1
  firebase_auth: ^5.5.0
  table_calendar: ^3.2.0
  firebase_storage: ^12.4.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  midtrans_sdk: ^0.4.0
  http: ^1.1.0
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # ------------- LOCAL ASSETS -------------#
  assets:
    - assets/lines/
    - assets/banners/
    - assets/logos/
    - assets/videos/
    - assets/images/
    - assets/images/gallery/
    - assets/animations/Onboarding1.json
    - assets/animations/Onboarding2.json
    - assets/animations/Onboarding3.json
    - assets/animations/successBooking.json
    - assets/animations/WaitingToResetPassword.json